[package]
name = "lisp-rpc-rust-parser"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core parser for Lisp-RPC, a lightweight, S-expression-based Remote Procedure Call protocol."

[dependencies]
itertools = "0"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
