[workspace]
resolver = "3"
members = [
  "parsers/lisp-rpc-rust-parser",
  "generators/lisp-rpc-rust-generator",
  "serializer",
  "server",
  "raw-data/lisp-rpc-rust-raw-data",

  "generators/lisp-rpc-rust-generator-macro", # deprecated

  "examples/rust/plain-mode-read-and-write-data",
  "examples/rust/serialize-struct-to-lisprpc",
  "examples/rust/server-with-custom-structure",
  "examples/rust/server-with-tcp",
]

[workspace.package]
license = "MIT"
repository = "https://github.com/ccqpein/lisp-rpc"
homepage = "https://github.com/ccqpein/lisp-rpc"

[profile.dev]
opt-level = 0
codegen-units = 256

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = "abort"

[workspace.dependencies]
lisp-rpc-rust-parser = { version = "0.1.6", path = "parsers/lisp-rpc-rust-parser" }
lisp-rpc-rust-generator = { version = "0.1.5", path = "generators/lisp-rpc-rust-generator" }
lisp-rpc-rust-serializer = { version = "0.1.1", path = "serializer" }
lisp-rpc-rust-server = { version = "0.1.2", path = "server" }
lisp-rpc-rust-raw-data = { version = "0.1.1", path = "raw-data/lisp-rpc-rust-raw-data" }

# deprecated
lisp-rpc-rust-generator-macro = { version = "0.1.0", path = "generators/lisp-rpc-rust-generator-macro" }
