[package]
name = "lisp-rpc-rust-generator-macro"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Procedural macro helper for generating Lisp-RPC client and server code."

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
convert_case = "0"
