#+TITLE: Lisp-RPC (Common Lisp Implementation)

The Common Lisp implementation of ~lisp-rpc~. 

* Install

If you use the ~quicklisp~, you can clone this file to ~~/quicklisp/local-projects~. And load this sys in your Lisp environment.

Then you can run the ~./make.sh~ (need ~sbcl~ installed) and get the execution file ~lisp-rpc-gen~ for spec generation mode.

* Usage

** Homoiconicity usage

Since the Lisp's dark magic -- homoiconic, we can just call the lisp-rpc data as the normal function call.

Check this [[file:examples/homoiconic.lisp][example]] for more details.

** Plain Mode

Parse raw lisp-rpc S-expression strings into raw data objects. 

Check this [[file:examples/raw-data.lisp][example]] for more details.

** Spec Mode & Code Generation

Just like the rust version, we can generate the lisp code from spec. Like this [[file:examples/spec-demo.lisp][spec]], we can run 

#+begin_src shell
  lisp-rpc-gen gen spec-demo.lisp
#+end_src

and then we get the generated ~demo~ package code.

** RPC Server

The Common Lisp RPC server runs on **Woo** (an asynchronous, high-performance HTTP server built on libev).

*** Server Example:

#+begin_src lisp
  (use-package :lisp-rpc-server)

  ;; 1. Initialize server
  (defparameter *server* (make-rpc-server :port 5000))

  ;; 2. Register handler (validated against rpc-endpoint-p)
  (register-rpc-handler *server* 'demo:get-book
    (lambda (req)
      ;; req is automatically deserialized into a #S(DEMO:GET-BOOK ...) struct
      (demo:make-book-info
       :title (demo:get-book-title req)
       :id "12345")))

  ;; 3. Start server
  (start-server *server*)
#+end_src

* APIs

[[file:raw-data.lisp][raw-data.lisp]]

| Symbol                          |                             |
|---------------------------------+-----------------------------|
| lisp-rpc-raw-data:raw-data      | major structure of raw data |
| lisp-rpc-raw-data:make-raw-data | make the raw-data struct    |
|                                 |                             |
