[package]
name = "lisp-rpc-rust-server"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Server implementation for Lisp-RPC, supporting Actix Web integration and schema-defined, type-checked RPC."

[dependencies]
actix-web = "4"
anyhow = "1"
lisp-rpc-rust-serializer = { workspace = true }
serde = { version = "1", features = ["derive"] }
